#BTE-PlotSystem Configuration File
database:
  name: name
  username: username
  password: password
outlines-schematic-path: null
finished-schematic-path: null
spawn-point:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
holograms:
